---

- name: Install nginx
  apt:
    state: present
    name: nginx

- name: Configure nginx
  copy:
    content: "{{ nginx_conf }}"
    dest: "/etc/nginx/sites-enabled/default"
  notify: reload nginx