---

# After running this playbook on a new machine, you'll need either to:
# - Rsync /var/www/pycon/fr/ from another server or a backup.
# - Redeploy every sites (to run pelican / frozen-flask / ...).

- hosts: webservers
  tasks:
    - name: Basic setup
      include_role: name=common

    - name: Users setup
      include_role: name=users

    - name: Setup watshyFr
      include_role: name=nginx
      vars:
        nginx_conf: |
            server {
                listen 443 ssl;
                ssl_certificate /etc/letsencrypt/live/watshy.fr/fullchain.pem; # managed by Certbot
                ssl_certificate_key /etc/letsencrypt/live/watshy.fr/privkey.pem; # managed by Certbot
                include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
                ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

                add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
                add_header X-Frame-Options "DENY";
                add_header X-Content-Type-Options "nosniff";
                add_header X-XSS-Protection "1; mode=block";
                add_header Content-Security-Policy "default-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'";

                server_name watshy.fr;
                index index.html;

                location ~ /\. {
                    deny all;
                }

                location / {
                    root /home/github/Portfolio;
                }

            }

            server {
                listen 443;
                server_name restaurants.watshy.fr;

                location / {
                    include proxy_params;
                    proxy_pass http://unix:/home/github/Restaurants/restaurants.sock;
                }
            }

            server {
                listen 80 ;
                listen [::]:80 ;
                server_name _;
                return 301 https://$host$request_uri;
            }