---

# Repo Portfolio
- name: Clone Portfolio master
  git:
    repo: https://github.com/Watshy1/Portfolio.git
    dest: /home/github/Portfolio
    single_branch: yes
    version: master
  become: true
  become_user: github

# Repo Restaurants
- name: Configure service restaurants
  copy:
    content: |
      [Unit]
      Description=Gunicorn instance to serve restaurants project
      After=network.target

      [Service]
      User=github
      Group=www-data
      WorkingDirectory=/home/github/Restaurants
      Environment="PATH=/home/github/Restaurants/.venv/bin"
      ExecStart=/home/github/Restaurants/.venv/bin/gunicorn --workers 3 --timeout 120 --bind unix:restaurants.sock -m 007 hello:app

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/restaurants.service
    owner: root
    group: root
    mode: 0755
  notify: reload daemon

- name: Delete directory Restaurants
  file:
    path: /home/github/Restaurants
    state: absent

- name: Clone Restaurants master
  git:
    repo: https://github.com/Watshy1/Restaurants.git
    dest: /home/github/Restaurants
    single_branch: yes
    version: master
  become: true
  become_user: github

- name: Create env for Restaurants
  command: python3 -m venv /home/github/Restaurants/.venv
  become: true
  become_user: github

- name: Install dependences for Restaurants
  command: /home/github/Restaurants/.venv/bin/python -m pip install Flask gunicorn overpy requests
  become: true
  become_user: github
  notify: restart restaurants