---

- name: Configure hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: Configure login message
  copy:
    content: |
      -----------------------------------------------------------------------------
      --------------- __          __  _______ _____ _    ___     __ ---------------
      --------------- \ \        / /\|__   __/ ____| |  | \ \   / / ---------------
      ---------------  \ \  /\  / /  \  | | | (___ | |__| |\ \_/ /  ---------------
      ---------------   \ \/  \/ / /\ \ | |  \___ \|  __  | \   /   ---------------
      ---------------    \  /\  / ____ \| |  ____) | |  | |  | |    ---------------
      ---------------     \/  \/_/    \_\_| |_____/|_|  |_|  |_|    ---------------
      -----------------------------------------------------------------------------
    dest: /etc/motd
    owner: root
    group: root
    mode: 0755

- name: Configure localhost
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 localhost"
    owner: root
    group: root
    mode: 0644

- name: Configure FQDN
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"
    owner: root
    group: root
    mode: 0644

- package: name=nftables state=present

- name: Copy nftables rules
  copy:
    content: |
      #!/usr/sbin/nft -f

      flush ruleset

      table inet filter {
              chain input {
                      type filter hook input priority 0;
              }
              chain forward {
                      type filter hook forward priority 0;
              }
              chain output {
                      type filter hook output priority 0;
              }
      }
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0755
  notify: reload nftables

- service: name=nftables enabled=yes state=started daemon_reload=yes

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install some usefull packages
  apt:
    state: present
    name:
        - aptitude
        - emacs-nox
        - fail2ban
        - git
        - htop
        - man
        - ncdu
        - needrestart
        - ntp
        - python3
        - python3-dev
        - python3-pip
        - python3-setuptools
        - python3-venv
        - python3-wheel
        - rsync
        - sudo
        - tcpdump
        - nano

- name: Set authorized SSH keys for root user
  authorized_key:
    user: root
    state: present
    key: "{{ root_authorized_keys }}"

- name: Ensure mlocate and locate are not installed
  apt:
    name: ["mlocate", "locate"]
    state: absent

# From https://infosec.mozilla.org/guidelines/openssh
- name: SSHd hardening
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK (KexAlgorithms, Ciphers, MACs)"
    path: /etc/ssh/sshd_config
    state: present
    create: true
    block: |
        HostKey /etc/ssh/ssh_host_ed25519_key
        HostKey /etc/ssh/ssh_host_rsa_key

        AuthenticationMethods publickey
        LogLevel VERBOSE
  notify: restart sshd
  tags: ssh